### ISSUE TITLE
What is this situation?  4.0.0 and 4.0.1

### ISSUE THREAD

**Issue by yiyubinglan** [MAnggiarMustofa/GI-Download-Library#79]
https://d3ln624mszu7ty.cloudfront.net/client_app/download/pc_zip/20230821151229_NAlBxGiyKlVXWZQJ/GenshinImpact_4.0.1.zip

ERROR
The request could not be satisfied.

Generated Mon, 28 Aug 2023 08:20:04 GMT
Request ID: ptNQjiP3KIUMzpHy19nX_wywOZxolvrp4jOXke2hEScQ-_0bBWYb_g==

**Comment by keitarogg** [comment]
cloudfront issue

**Comment by keitarogg** [comment]
mihoyo closed some mirrors
